import Navbar from "../elements/navbar"
import Footer from "../elements/footer"
import Head from 'next/head'
import { ToastContainer } from "react-toastify"
import { Col, Row } from "react-bootstrap"

export default function Layout({ 
  children
 }) {
  return (
    <>
      <Head>
        <title>Rolling Glory Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        {children}
      </main>
      <Footer />
      <ToastContainer
        position="top-center"
        autoClose={3000}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
      />
    </>
  )
}